default: &default
  adapter: postgresql
  encoding: unicode
  username: muratcayir
  password: 1234
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: kitap_yonetimi_development

test:
  <<: *default
  database: kitap_yonetimi_test

production:
  <<: *default
  database: kitap_yonetimi_production
  username: kitap_yonetimi
  password: <%= ENV["KITAP_YONETIMI_DATABASE_PASSWORD"] %>
